---
# note: this workflow definition will create a project from
# the cookiecutter template to test the results
name: run tests

on:
  push:
    branches: [main, templatize-via-cookiecutter]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_FROM: type=gha,scope=gc-cloud-storage-bucket
      DAGGER_CACHE_TO: type=gha,mode=max,scope=gc-cloud-storage-bucket
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Install environment
        run: poetry install --no-interaction --no-ansi
      - name: Create cookiecutter project with defaults
        run: poetry run cookiecutter . --no-input --output-dir tests
      - name: Change dir into the testing dir
        run: cd tests/lab-initiative-bucket
      - name: Simulate git for pre-commit checks
        run: |
          # set username and email
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          # init and add all content to be checked
          git init
          git add .
          git commit -m "A commit to perform pre-commit checks"
      - name: Dagger
        uses: dagger/dagger-for-github@v4
        with:
          cmds: |
            project update
            do test
